### ISSUE TITLE
-DdependencyInjection can cause duplicates

### ISSUE THREAD

**Issue by k-wall** [release-engineering/pom-manipulation-ext#1013]
I'm using `-DdependencyInjection` to inject a `dependency` into `dependencyManagement`.  The dependency already exists, so my intent to overwrite the existing dependency, changing the version.   I notice that PME actually injects the dependency, leaving the existing one in place.

Maven then warns about the duplicate.

```
[WARNING] Some problems were encountered while building the effective model for org.apache.flink:flink-annotations:jar:1.19.1.temporary-redhat-00024
[WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.apache.flink:flink-shaded-asm-9:jar -> version 9.5.0.17-0-temporary-redhat-00013 vs 9.5-${flink.shaded.version} @ org.apache.flink:flink-parent:1.19.1.temporary-redhat-00024, /private/tmp/flink/pom.xml, line 336, column 16
[WARNING]
```

Checking the effective POM, I can see that the injected one is replacing the first, so it is having the effect I wish.

**Expected behaviour:**

The original dependency to overwrite the original one.
There to be no dependency warnings.

**Additional Information**

I also tried to express the override as `-DdependencyRelocations`, but it seems this is ineffective against dependencyManagement dependenciies.

**Comment by rnc** [comment]
Can you give me your command line / project / etc to reproduce the issue?

**Comment by k-wall** [comment]
I've shared details with you within Red Hat (slack thread)
