### ISSUE TITLE
Inject plugin executions from a remote POM

### ISSUE THREAD

**Issue by pgier** [release-engineering/pom-manipulation-ext#107]
Related to issue #91, we need a way to inject plugin executions (in addition to configuration), to fully replace the old VMan process of setting the parent POM.
For EAP specifically this is used to execute the build number maven plugin to generate a build timestamp, and the source plugin to generate the source jar.
The current pluginManagement option injects configuration, but does not add plugin executions from the <build><plugins/> section of the remote POM.

**Comment by rnc** [comment]
@pgier  : Is using profile injection a suitable resolution to this?

**Comment by pgier** [comment]
@rnc yes, I think profile injection is enough to resolve this.
