### ISSUE TITLE
dependencies with groupId == ${project.groupId} aren't aligned

### ISSUE THREAD

**Issue by jdcasey** [release-engineering/pom-manipulation-ext#113]
The problem is the ga(String, String) method, which doesn't accept a context project instance and does not perform expression substitution. 

All methods in IdUtils that produce a GA or GAV should probably accept a Model, Project, or MavenProject to supply both the POM and POM properties to an interpolator that can do the string substitutions.

**Comment by jdcasey** [comment]
I don't think we should adjust the version fields, just to be clear...but groupId and artifactId are used for matching with dependencyManagement, and should definitely be subbed.

**Comment by rnc** [comment]
@jdcasey What case were you envisaging with this? I have tried a test with e.g.
```
    <dependencies>
      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>child-module-dependency-override-child</artifactId>
        <version>1.0-SNAPSHOT</version>
      </dependency>
```
and have noticed that the project.groupId gets expanded out.

**Comment by jdcasey** [comment]
seems like this has been fixed along the way. Closing.
