### ISSUE TITLE
Location of build.properties file

### ISSUE THREAD

**Issue by sbadakhc** [release-engineering/pom-manipulation-ext#118]
Its seems as though the default location of the build.properties used but the pom-manipulation-ext is clobbering an identically named file with projects that are built with ant.  The original bug was filed against the buildmetadata-maven-plugin but we modified the default property that ships with buildmetadata-maven-plugin for pom-manipulation-ext.  The original bug is filed as RT336220.  would it be possible to revert to the default property?

**Comment by jdcasey** [comment]
@rnc can we use the default location (`target/classes/META-INF/build.properties`) or should we set it to something like `${basedir}/bmmp-build.properties`?

It seems like there must be a reason we aren't including this in the jar (maybe so it appears in the project source zip?)...

**Comment by rnc** [comment]
We didn't include it in the target directory so it would be included in the sources. 

Perhaps build.properties is not the best name ?

**Comment by sbadakhc** [comment]
How about build.metadata.  That would also give hint to how it was created?

**Comment by rnc** [comment]
+1

**Comment by jdcasey** [comment]
Marking as closed (merged PR)
