### ISSUE TITLE
Detect use of ${project.version} in dependencies

### ISSUE THREAD

**Issue by jdcasey** [release-engineering/pom-manipulation-ext#121]
This can be especially dangerous if the POM is a BOM (or a parent POM that someone might inherit from outside of its own project).

When either of these are used, the consuming project's version is used for ${project.version}, NOT the intended version from the original BOM/POM.

We should be able to detect this - on both ends, producing and consuming - and take one of three actions:

* warn (producer side...this is weak, I'm not a fan)
* fail the build (producer side)
* correct seamlessly (consumer and producer)

**Comment by jdcasey** [comment]
if packaging != pom, we can probably ignore this issue...you can't inherit from a POM unless it's got that packaging, and I would hope that the same holds for BOMs (though I haven't verified it in the Maven codebase).

**Comment by rnc** [comment]
Regarding warn - given the amount of output already it is likely warnings would be missed.

What about failing the build if we detect the consumption of an invalid [use of project.version] POM ? 

Surely if the producer is corrected during the build, the consumer would not have to be corrected?...it would be transparent?

**Comment by jdcasey** [comment]
Agreed, the simplest fix would be to fix on the producer side and let the consumption just detect/fail. The only problem is it won't address the use of older artifacts/POMs.

Also, it might be worth examining if this still causes problems on new versions of Maven. Someone mentioned to me that they couldn't reproduce the problem from my description when using a recent version.

**Comment by rnc** [comment]
I have tested with Maven 3.2.5. I can reproduce the problem when using inheritance but not when using import.

**Comment by rnc** [comment]
Fixed by #125 and #125
