### ISSUE TITLE
PomPeek : use galley version of pompeek

### ISSUE THREAD

**Issue by rnc** [release-engineering/pom-manipulation-ext#139]
(and migrate unit tests to galley)

**Comment by rnc** [comment]
https://github.com/Commonjava/galley

https://github.com/Commonjava/galley/blob/master/maven/src/main/java/org/commonjava/maven/galley/maven/parse/PomPeek.java

**Comment by jdcasey** [comment]
Can we close this now?

**Comment by rnc** [comment]
Fixed in #149
