### ISSUE TITLE
Invalid dependencyExclusion doesn't fail the build

### ISSUE THREAD

**Issue by rnc** [release-engineering/pom-manipulation-ext#147]
If we have an invalid dependencyExclusion e.g. change 
```
-dependencyExclusion.junit\:*@*=
+dependencyExclusion.junit@*=
````
in `src/it/depex-multiple-wildcard/test.properties` then the exception thrown ( `org.commonjava.maven.atlas.ident.ref.InvalidRefException` ) is a RuntimeException and is not handled by ` org.commonjava.maven.ext.manip.ManipulationManager` or `org.commonjava.maven.ext.manip.ManipulatingEventSpy`

**Comment by rnc** [comment]
Turns out this is due to an InvalidRefException being thrown from ProjectRef.parse within DependencyManipulator. This leads onto a number of points:
 * We should ensure RuntimeExceptions thrown during PME do fail the build.
 * @jdcasey : should InvalidRefException be a RuntimeException or a normal Exception?
 * In a number of the Manipulators we catch the InvalidRefException, log a warning and continue. I think that we should fail the build in the case of an invalid configuration.

**Comment by jdcasey** [comment]
@rnc it should probably be a checked exception. I have a feeling this will have HUGE implications in terms of required code changes, though. It's probably something we should do, though.

**Comment by rnc** [comment]
Added https://github.com/Commonjava/atlas/issues/31
