### ISSUE TITLE
Refactor to version-sources SPI

### ISSUE THREAD

**Issue by jdcasey** [release-engineering/pom-manipulation-ext#152]
Versions we use:
- project
- parent?
- dependencies
- plugins

We currently load this information from one or more BOM-ish sources (something like a BOM but with pluginManagement is also supported), and from the maven repository itself in the case of the project version. 

We need to refactor all of this to use an SPI interface for retrieving versions in each category (using a batch request/response approach), then move the current logic into an implementation of this SPI.

This will enable us to provide alternative sources for this information besides formal Maven POMs and the Maven repository metadata.

**Comment by rnc** [comment]
Marking as fixed now.
