### ISSUE TITLE
REST client version-source SPI Implementation

### ISSUE THREAD

**Issue by jdcasey** [release-engineering/pom-manipulation-ext#153]
Once #152 is complete, we need to implement a REST client to talk to some external service via a well-documented domain model + service endpoint scheme. This service should batch all versions needed (maybe for all projects in the current workspace; but at least for a given project), in order to reduce network traffic, parsing time, etc.

This will be useful in larger build environments where we can use a service that exposes versions tracked in a database, rather than depend on having complete information in the maven repository and a set of well-maintained BOMs.

**Comment by rnc** [comment]
@VaclavDedik : Now #182 is merged could merge in https://github.com/VaclavDedik/maven-tooling-rest-client ?

**Comment by VaclavDedik** [comment]
@rnc Sure, so do I understand it correctly that I should place it in the io module?

**Comment by rnc** [comment]
@VaclavDedik  : Yes please.

**Comment by rnc** [comment]
Fixed by #183
