### ISSUE TITLE
Can version properties be resolved against sibling projects from where they're declared? 

### ISSUE THREAD

**Issue by jdcasey** [release-engineering/pom-manipulation-ext#191]
See DependencyRESTManipulator.resolveProperties(..) in forthcoming PR for example. There are probably others, especially related to property manipulation...

**Comment by jdcasey** [comment]
Currently thinking map projects by ProjectRef key, then use getParent() to traverse up the ancestry when resolving properties. That will leave out properties defined in siblings/uncles/etc. of the declaring POM.

**Comment by rnc** [comment]
Similar code in CommonDependencyManipulation::updateProperties will recursively resolve properties to set a new value. If the property isn't found it injects it at top level.
