### ISSUE TITLE
Fix JDK version in IT: remote-dependency-management-parent

### ISSUE THREAD

**Issue by jdcasey** [release-engineering/pom-manipulation-ext#211]
Looks like it's expecting JDK 1.7+ when run from the it-ext directory (for the extension packaging, I take it?). It's strange, because I think this is coming from the jboss-parent (set at version 15 in the resulting project in it-ext, from what I can tell)...but in src/it it's jboss-parent:8 ...so I gather that it's resetting the parent version (probably the point of the test). However, it looks like we may need to peg the source/target versions (possibly for the enforcer plugin as well as the compiler plugin) to use 1.6. Either that, or we could concoct our own dummy parent to use in place of jboss-parent.

The reason this is failing in CI is that we're forcing it to build with JDK 1.6, so this is the requirement for replicating the failure locally.

@rnc I'm giving this to you initially since it looks like it was your PR that introduced the error, but if someone else has cycles to work on it, feel free to reassign as necessary, obvs. :)

**Comment by rnc** [comment]
@jdcasey thanks ;-) I used jboss-parent ... just as a dummy pom parent to be honest and to avoid the overhead of setting up more setup/*. A possibly fix might be to use a very early jboss-parent?

**Comment by rnc** [comment]
Fixed by #212
