### ISSUE TITLE
Strict mode priority with respect to explicit version overrides.

### ISSUE THREAD

**Issue by rnc** [release-engineering/pom-manipulation-ext#214]
After speaking to Ryan / Julian it might be worth considering explicitOverrides e.g.

`dependencyExclusion.junit\:junit@org.commonjava.maven.ext\:depmgmt-strict-mode-override=4.12`

to have a higher priority than strictMode and therebye ignore it.

Also `applyExplicitOverrides` does not check strictMode when apply explicit overrides (although they are checked in properties) - this should be made consistent.

**Comment by ryanzhang** [comment]
+1.
We need to have a way to allow a whitelist to override for exceptional cases in order to use the strictMode and also allow the  exception at the same time.
Currently we used dependencyExclusion to specify the exceptional cases.

**Comment by rnc** [comment]
See PR #215

**Comment by rnc** [comment]
Fixed by #215
