### ISSUE TITLE
Extension throws error when there is a blank artifactID in a dependency

### ISSUE THREAD

**Issue by pgier** [release-engineering/pom-manipulation-ext#221]
In the EAP build there is a profile in the testsuite which sets different artiactId depending on which jdbcdriver you are using.  By default no jdbcdriver is set if the testsuite is not running.  When the extension encounters this dependency

DEBUG util.py:257:  [main] ERROR o.c.m.ext.manip.ManipulatingEventSpy - Extension failure
DEBUG util.py:257:  org.commonjava.maven.atlas.ident.ref.InvalidRefException: ProjectId must contain non-empty groupId AND artifactId. (Given: 'jdbcdrivers':'')
DEBUG util.py:257:  	at org.commonjava.maven.atlas.ident.ref.SimpleProjectRef.<init>(SimpleProjectRef.java:41) ~[pom-manipulation-ext-1.7.jar:1.7]
DEBUG util.py:257:  	at org.commonjava.maven.atlas.ident.ref.SimpleProjectVersionRef.<init>(SimpleProjectVersionRef.java:59) ~[pom-manipulation-ext-1.7.jar:1.7]
DEBUG util.py:257:  	at org.commonjava.maven.atlas.ident.ref.SimpleProjectVersionRef.<init>(SimpleProjectVersionRef.java:78) ~[pom-manipulation-ext-1.7.jar:1.7]
DEBUG util.py:257:  	at org.commonjava.maven.ext.manip.impl.ProjectVersioningManipulator.applyVersioningChanges(ProjectVersioningManipulator.java:283) ~[pom-manipulation-ext-1.7.jar:1.7]
DEBUG util.py:257:  	at org.commonjava.maven.ext.manip.impl.ProjectVersioningManipulator.applyChanges(ProjectVersioningManipulator.java:141) ~[pom-manipulation-ext-1.7.jar:1.7]
DEBUG util.py:257:  	at org.commonjava.maven.ext.manip.ManipulationManager.applyManipulations(ManipulationManager.java:200) ~[pom-manipulation-ext-1.7.jar:1.7]
DEBUG util.py:257:  	at org.commonjava.maven.ext.manip.ManipulationManager.scanAndApply(ManipulationManager.java:135) ~[pom-manipulation-ext-1.7.jar:1.7]
DEBUG util.py:257:  	at org.commonjava.maven.ext.manip.ManipulatingEventSpy.onEvent(ManipulatingEventSpy.java:112) ~[pom-manipulation-ext-1.7.jar:1.7]
DEBUG util.py:257:  	at org.apache.maven.eventspy.internal.EventSpyDispatcher.onEvent(EventSpyDispatcher.java:108) [maven-core-3.2.3.jar:3.2.3]
DEBUG util.py:257:  	at org.apache.maven.eventspy.internal.EventSpyExecutionListener.projectDiscoveryStarted(EventSpyExecutionListener.java:47) [maven-core-3.2.3.jar:3.2.3]
DEBUG util.py:257:  	at org.apache.maven.lifecycle.internal.DefaultExecutionEventCatapult.fire(DefaultExecutionEventCatapult.java:57) [maven-core-3.2.3.jar:3.2.3]
DEBUG util.py:257:  	at org.apache.maven.lifecycle.internal.DefaultExecutionEventCatapult.fire(DefaultExecutionEventCatapult.java:42) [maven-core-3.2.3.jar:3.2.3]
DEBUG util.py:257:  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:238) [maven-core-3.2.3.jar:3.2.3]
DEBUG util.py:257:  	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154) [maven-core-3.2.3.jar:3.2.3]
DEBUG util.py:257:  	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582) [maven-embedder-3.2.3.jar:3.2.3]
DEBUG util.py:257:  	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214) [maven-embedder-3.2.3.jar:3.2.3]
DEBUG util.py:257:  	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158) [maven-embedder-3.2.3.jar:3.2.3]
DEBUG util.py:257:  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_60]
DEBUG util.py:257:  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_60]
DEBUG util.py:257:  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_60]
DEBUG util.py:257:  	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_60]
DEBUG util.py:257:  	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289) [plexus-classworlds-2.5.1.jar:na]
DEBUG util.py:257:  	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229) [plexus-classworlds-2.5.1.jar:na]
DEBUG util.py:257:  	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415) [plexus-classworlds-2.5.1.jar:na]
DEBUG util.py:257:  	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356) [plexus-classworlds-2.5.1.jar:na]

**Comment by rnc** [comment]
Fixed by #222
