### ISSUE TITLE
On Windows, the pom's are written with CR / LF, although the original only contains LFs

### ISSUE THREAD

**Issue by torsten-liermann** [release-engineering/pom-manipulation-ext#242]
On Windows, the pom's are rewritten with CR + LF, although the original only contains LF. Please keep the orginal line seperation.

Thanks!

**Comment by rnc** [comment]
Thanks for the report. I can confirm it uses the system to determine the line ending to use. It should probably parse the file and use the original file contents instead.

**Comment by rnc** [comment]
Closed with #244
