### ISSUE TITLE
If the pom's version is a variable it's not expanded

### ISSUE THREAD

**Issue by mkolesni** [release-engineering/pom-manipulation-ext#253]
In https://git.opendaylight.org/gerrit/controller there are some poms where the artifact's version is a variable.
When running something like: mvn -B -Dversion.suffix=test deploy
The version is replaced with the same value suffixed by -test
So for example ${version} would be replaced with ${version}-test

This causes maven to fail with something about 'dependencies.dependency.version must be a valid version'

For reference, my maven & java version:
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-29T09:52:58+03:00)
Java version: 1.7.0_91, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.91-2.6.2.1.el7_1.x86_64/jre

**Comment by rnc** [comment]
I can reproduce this. We have much of the relevant code already to resolve properties and follow the property to update the correct value ; I think this is feasible to do.
