### ISSUE TITLE
plugin config injection removes properties

### ISSUE THREAD

**Issue by pgier** [release-engineering/pom-manipulation-ext#255]
When I have a remote plugin config pom which contains properties in the config, the extension inserts the configuration but no longer contains the properties.  For example the jboss-parent pom contains jar plugin config which looks like this:
```xml
    <manifestEntries>
        <Java-Version>${java.version}</Java-Version>
    </manifestEntries>
```
but PME inserts only this into the local POM's jar plugin config:
```xml
    <manifestEntries>
        <Java-Version/>
    </manifestEntries>
```

**Comment by rnc** [comment]
I think the issue is within ModelIO when it reads the remote configuration.

**Comment by pgier** [comment]
Verified that the fix from @rnc fixes the issue
