### ISSUE TITLE
Plugin config injection does not take into account properties in the local build

### ISSUE THREAD

**Issue by pgier** [release-engineering/pom-manipulation-ext#257]
The jboss-parent pom has plugin config for the maven compiler plugin which looks like this
```xml
  <properties>
    <maven.compiler.target>1.6</maven.compiler.target>
  </properties>
  ...
  <configuration>
    <target>${maven.compiler.target}</target>
  </configuration>
```
When this is injected into a build, the property is resolved to the value set in the jboss-parent pom and it ignores local system properties.
```xml
  <configuration>
    <target>1.6</target>
  </configuration>
```
This means that after plugin injection (compared to POM inheritance) I can no longer override this setting at run time.  When the value of ${maven.compiler.target} is resolved, it should take into account whether I set the local property "-Dmaven.compiler.target".

**Comment by rnc** [comment]
Related : #91

**Comment by rnc** [comment]
Should be fixed now
