### ISSUE TITLE
Do not inject plugin management when there is no configuration

### ISSUE THREAD

**Issue by pgier** [release-engineering/pom-manipulation-ext#269]
Also see related #91 and #258 

The recent change in #258 caused all pluginManagement to be injected including plugin definitions which do not include configuration.  I think it would be better to only inject a plugin management when there is some content in <configuration/>.  Overriding the plugin version by itself (without configuration) can be a bit risky because the injected version may not be compatible with the existing plugin configuration.

**Comment by pgier** [comment]
Just thinking about this some more, I think it's ok to leave the current behavior as-is and just inject everything from pluginManagement into the local POM.  Implementing this change would make the logic of the plugin and the documentation a little more complex.

**Comment by jdcasey** [comment]
It might be good to review how managed dependencies are injected, and make it consistent. WDYT?

**Comment by pgier** [comment]
Managed dependencies wouldn't normally have any configuration, other than maybe excludes, so they are always injected into dependencyManagement.  I think we should do the same with pluginManagement for now, and just close this issue as won't fix.

**Comment by pgier** [comment]
Closing this issue since we agreed that for now it's better to keep the current behavior.
