### ISSUE TITLE
Build fails using JDK 8

### ISSUE THREAD

**Issue by pgier** [release-engineering/pom-manipulation-ext#271]
When building with JDK 8, the animal sniffer maven plugin causes the build to fail with the error

[ERROR] Failed to execute goal org.codehaus.mojo:animal-sniffer-maven-plugin:1.13:check (check-java-api) on project pom-manipulation-core: Execution check-java-api of goal org.codehaus.mojo:animal-sniffer-maven-plugin:1.13:check failed. IllegalArgumentException -> [Help 1]

**Comment by rnc** [comment]
I think we just need to update to animal-sniffer 1.14

**Comment by rnc** [comment]
Fixed by #271
