### ISSUE TITLE
Dependencies inside plugins aren't handled

### ISSUE THREAD

**Issue by mkolesni** [release-engineering/pom-manipulation-ext#283]
If there's a dependency inside a plugin it's not getting processed.

For example:
https://github.com/opendaylight/yangtools/blob/release/lithium-sr2/common/parent/pom.xml#L311

When running a suitable BOM with -DpluginManagement will not change the version of the dependency inside the plugin (maven-sal-api-gen-plugin) but will correctly change the plugin's (yang-maven-plugin) version.

Not sure how this should be handled if you don't want to change the plugin's version but only it's dependency version, perhaps if in the BOM you don't specify a new version for the plugin itself then it will just handle it's dependencies.
Another option is to do this replacement as part of -DdependencyManagement

**Comment by rnc** [comment]
Fixed by #293
