### ISSUE TITLE
PluginMgmt / Plugin configuration injection

### ISSUE THREAD

**Issue by rnc** [release-engineering/pom-manipulation-ext#292]
If a POM has a plugin mgmt and a plugin section which both contain a plugin. I noticed while looking at #283 that we currently inject the configuration into both pluginManagement and plugins section. It might be possible to optimise this in certain situations e.g. if the plugin section does not have an executions/configuration, just changing the management section might be sufficient.

@pgier / @jdcasey - thoughts?

**Comment by jdcasey** [comment]
yeah, makes sense to me, as long as we're covering the bases and not allowing a local version override in the build/plugins section to remain intact (or similar for config)

**Comment by rnc** [comment]
Actually, rereading the code, in #91 we dealt with this by only injecting the configuration in the pluginMgmt block. Therefore I think this can be closed.
