### ISSUE TITLE
SCM Revision Fetching

### ISSUE THREAD

**Issue by rnc** [release-engineering/pom-manipulation-ext#301]
I think we should add
```
<queryRangeInDays>365</queryRangeInDays>
```
to the metadata plugin configuration otherwise it doesn't always find a useful revision (it defaults to 30).

**Comment by jdcasey** [comment]
+1

**Comment by rnc** [comment]
Actually, on second thoughts I think its a bug in upstream (I was testing the extra spi provider which still needs upstream). Double checking I am having trouble reproducing it now. Closing for now.
