### ISSUE TITLE
Add an opensource license like apache 2 to any PME generated files

### ISSUE THREAD

**Issue by paulgallagher75** [release-engineering/pom-manipulation-ext#302]
Could we add a license to the top of files like settings.xml which has references to PME in it and build.metadata which is generated via the buildmetadata-maven-plugin which I believe is added by PME.

Both these files are in the top level of the project.

Some projects like artemis run the apache-rat-plugin which does a license check on all files that are not in the 'exclude' list, and these 2 files fail the check which fails the build overall.

At present I just use patches to add these to the exclude list in the pom.xml however this change cannot be pushed upstream as they would never see this problem

**Comment by rnc** [comment]
Does the apache-rat-plugin check for certain license types? What patch are you adding? If we add a particular license, would it still fail the check if the plugin has been heavily restricted?

**Comment by paulgallagher75** [comment]
Yes the rat plugin by default checks for certain licenses however the common opensource ones do not seem to fail it. 

It has the ability to check for custom licenses as well, just in case, however I think it would be best to chose a common opensource license like the ASF apache 2.0 copyright.

**Comment by jdcasey** [comment]
interesting, so it wouldn't fail if the rest of the project was GPLv3 but these few files were APLv2?

**Comment by rnc** [comment]
Does Artemis have a particular configuration of it? What license does your patch inject?

**Comment by paulgallagher75** [comment]
A little miscomunication here, the patch I mentioned is for prod buildsystem just excluded the generated files in the pom.xml, not a patch for PME.

The license that is used in AMQ7 that works fine is the Apache 2.0 copyright, example from the pom file -

**Comment by paulgallagher75** [comment]
Alternatively you could use the same approach I do and make PME add/alter the </excludes> section of the rat plugin and add in the files that are generated example -

         <plugin>
            <groupId>org.apache.rat</groupId>
            <artifactId>apache-rat-plugin</artifactId>
            <version>0.11</version>
            <configuration>
               <reportFile>${activemq.basedir}/ratReport.txt</reportFile>
               <excludes>
                  ...
                  ...
                  <exclude>build.metadata</exclude>
                  <exclude>settings.xml</exclude>
               </excludes>
            </configuration>
         </plugin>

**Comment by jdcasey** [comment]
it'd be nice if we could add exclusions

**Comment by rnc** [comment]
@jdcasey - are you suggested modifying the rat plugin if it can be found? What if the plugin is inherited? 
More of a 'nuclear' option - but are we really interested in running the rat plugin in a prod build i.e. why not just remove the plugin?

**Comment by rnc** [comment]
Another option might be to use `-Drat.ignoreErrors=true` or `-Drat.skip=true` (from looking at https://creadur.apache.org/rat/apache-rat-plugin/check-mojo.html )

**Comment by jdcasey** [comment]
+1 for ignore or skip. I hadn't considered the inheritance use case, but you're right...and reconfiguring in the child project would be horribly complex. I have to say I'm skeptical that just using APLv2 for the generated files would work in every case where the rat plugin is used...

**Comment by rnc** [comment]
@paulgallagher75 @jdcasey If no objections, I suggest closing this.

**Comment by jdcasey** [comment]
agreed

**Comment by paulgallagher75** [comment]
Last comment, I found using the -Drat.numUnapprovedLicenses=2 then allows the two files that are generated to be counted toward a max of 2 unapproved licenses, anymore after that has to be other errors
