### ISSUE TITLE
PME ignores <![CDATA[]]> xml escapes

### ISSUE THREAD

**Issue by jonathanchristison** [release-engineering/pom-manipulation-ext#304]
In some circumstances PME has made alterations to the pom which breaks inline html/js.
You can see this in the diff of a pom. I've added the diff, orginal and PME altered files - https://gist.github.com/jonathanchristison/1f9da4bc4152ed4bc854.

Although I haven't tested the end result I suspect it will escape the html and break its parsing upon rendering.

**Comment by rnc** [comment]
The problem appears to be in the read components. When it goes into plexus-utils (from MavenXpp3Reader) it drops the CDATA statements.

**Comment by jdcasey** [comment]
I think it's actually a problem with the maven-model-jdom-support artifact, specifically with MavenJDOMWriter. This class re-reads the Document from file and merges changes from the Model instance back in. It does this specifically so it can preserve things like comments (and, well, CDATA)...it just seems like it's not yet smart enough to detect the presence of CDATA inside an element, and preserve that.

One thing that would be a hard edge case to handle would be a mixture of "escaped" text and CDATA in the same element...if that element's contents changed, it'd be pretty hard to determine what part should go in/outside the CDATA section.

**Comment by jdcasey** [comment]
See:

* https://github.com/jdcasey/maven-model-jdom-support/blob/master/src/main/java/org/apache/maven/model/io/jdom/MavenJDOMWriter.java
https://github.com/jdcasey/maven-model-jdom-support/blob/master/src/main/java/org/apache/maven/io/util/AbstractJDOMWriter.java#L113

**Comment by rnc** [comment]
@jdcasey : @jonathanchristison has tested this and said even though the diff looks huge, the result is the same (as it escapes on the write out)

**Comment by rnc** [comment]
Awaiting merge of https://github.com/Commonjava/maven-model-jdom-support/pull/5

**Comment by rnc** [comment]
@jdcasey And a new release https://github.com/Commonjava/maven-model-jdom-support/issues/6 please :-)

**Comment by jdcasey** [comment]
done: http://repo.maven.apache.org/maven2/org/commonjava/maven/maven3-model-jdom-support/1.4/
