### ISSUE TITLE
Implement relocation-manipulator

### ISSUE THREAD

**Issue by rnc** [release-engineering/pom-manipulation-ext#305]
Some product builds relocate community group:artifact so we should be able to dynamically change those e.g.

-DdependencyRelocations=oldGroupId:newGroupId,...

**Comment by rnc** [comment]
Something else to consider on this. Some of the relocations don't just change groupId but version e.g.

`org.foo:artifact:10.0.Final`
-->
`com.bar:artifact:7.0.ER5`

Changing the version is crossing over onto the dependencyExclusion force-version territory however. Rather than reimplementing the depExclusion code perhaps we can hook into it.

**Comment by jdcasey** [comment]
What about cases where you need to relocate the artifactId? I'm thinking of servlet-api -> the jboss equivalent artifact, for example. That would have the full GAV relocated, I think?

**Comment by rnc** [comment]
Good point. Our current use-case is only for groupId & version but I guess we should make it flexible enough just in case ;-)

**Comment by jdcasey** [comment]
well, I'm going to close this. I've released internally and publicly in 1.16
