### ISSUE TITLE
Extend to handle GAV relocation in the xml file for maven-assembly-plugin

### ISSUE THREAD

**Issue by paulgallagher75** [release-engineering/pom-manipulation-ext#328]
The relocation code that was added had the knock on effect that the xml file for the maven-assembly-plugin does not get relocated and therefore the distro contains the wrong artifacts e.g. (activemq-artemis for AMQ7)

The top level pom.xml -
```
         <dependency>
            <groupId>org.apache.tomcat</groupId>
            <artifactId>tomcat-servlet-api</artifactId>
            <version>8.0.23</version>
         </dependency>
```
BECOMES
```
         <dependency>
            <groupId>org.jboss.spec.javax.servlet</groupId>
            <artifactId>jboss-servlet-api_3.1_spec</artifactId>
            <version>1.0.0.Final-redhat-1</version>
         </dependency>
```
However the artemis-distribution/src/main/assembly/dep.xml which is used to drive the maven-assembly-plugin has -
```
            <include>org.apache.tomcat:tomcat-servlet-api</include>
```
When it should be changed to -
```
            <include>org.jboss.spec.javax.servlet:jboss-servlet-api_3.1_spec</include>
```

**Comment by rnc** [comment]
Currently PME only examines XML that are in the maven model not arbitrary XML files used by the assembly plugin. Also I believe the assembly plugin can use a slightly different format i.e. it doesn't specify version just group:artifact (and optionally type, classifier). 
A workaround would be to use the groovy plugin. It might be  possible to specify arbitrary extra files for PME to work on .... but what happens if they are not XML ?

**Comment by paulgallagher75** [comment]
The problem is that the dep.xml file is not part of the PME model that gets passed to the groovy script (I think, please correct if I am wrong), and when I added in 'groovy.utils.XmlParser or groovy.utils.XmlSlupper', they were not in the classpath when the groovy script runs under PME, as I don't know how to add arbitrary dependencies at runtime for PME I resorted to just using a patch file to change it.

I think this may have brought up the problem of runtime dependencies for PME, I think we need a way to config that through the meta info of the cfg files.

**Comment by jdcasey** [comment]
this is starting to sound more like we would need a "main" command for pom.xml files and another type (or multiple types?) of command that we could add to the PME execution to handle extra files. Assembly XMLs are definitely not going to the end of this...and at that point it's not a huge leap into processing Ant or even Gradle files.

Sorry if that overwhelms anyone, but IMO it's starting to look like a an opportunity for taking a quantum leap into a generalized standardization tool.

Also, it's worth mentioning that this same problem would happen in Indy right now if we relocated some of its deps...but it'd be in the shade plugin configuration in the POM, not in a separate file. Not sure how to handle that, but it does point to a need for extra processing within the POM to deal with those references.

**Comment by rnc** [comment]
And json files :-( : https://issues.jboss.org/browse/RHAPI-23

**Comment by rnc** [comment]
@jdcasey Currently we do have the ability to perform arbitrary manipulations on any type of file in the project via the groovy script plugin. However, as @paulgallagher75 has discovered, it needs to bundle in the groovy utils xml code. *However* this is somewhat unstructured and we could end up with people duplicating the same groovy script. Perhaps a more generic set of 'modders' capable of operating on e.g. plain txt, json, xml would be useful.

**Comment by rnc** [comment]
See also #344 and #343

**Comment by rnc** [comment]
Fixed by prior PRs.
