### ISSUE TITLE
Split the requests to DA not to excess a fixed limit

### ISSUE THREAD

**Issue by jbartece** [release-engineering/pom-manipulation-ext#334]
PME makes a request to DA to lookup artifacts using the DA endpoint /reports/lookup/gavs, but the request size is not limited, so the requests can contain hundreds of GAVs and it causes timeouts of the request.

We have to split the requests to requests with 30 artifacts at maximum.

The code should look like this:
for ( subSetOfGavs : allGavs)
{ lookupUsingDA(subSetOfGavs); doSomeActions(); }

Original code:
lookupUsingDA(allGavs);
doSomeActions();

**Comment by rnc** [comment]
Fixed by #336
