### ISSUE TITLE
PME should fail when updating version variable to different versions

### ISSUE THREAD

**Issue by janinko** [release-engineering/pom-manipulation-ext#338]
PME should detect situation, when it tries to update one variable with different versions and fail at that moment. If it doesn't it can leave pom files in state where some dependencies doesn't exist.

**Comment by rnc** [comment]
Note for reference : this issue concerns the scenario where a dependency with a property is updated to `1.0.rebuild-1` and another, which uses the same property, is updated to `1.0.rebuild-4`
