### ISSUE TITLE
XML updater cannot handle ':' in the string replacement

### ISSUE THREAD

**Issue by paulgallagher75** [release-engineering/pom-manipulation-ext#353]
xmlUpdate=artemis-distribution/src/main/assembly/dep.xml://include[starts-with(.,'org.apache.tomcat')]:org.jboss.spec.javax.servlet:jboss-servlet-api_3.1_spec

The replacement string has a ':' in it which would be parsed based on the separator for PME is ':'

**Comment by rnc** [comment]
Probably need to check comma separation (and in the json facility as well).

**Comment by rnc** [comment]
Fixed by #354
