### ISSUE TITLE
Feature request: repositories entries in specific POM

### ISSUE THREAD

**Issue by jcoleman0redhat0com** [release-engineering/pom-manipulation-ext#374]
Adding <repository> entries to POM files currently only works on the top-level POM.  It would be very convenient if the <repository> entry could be added to a specific POM.  For example, in a heirarchy:
```
  |- pom.xml
  '- examples
      '-pom.xml
```
the <repository> entry is required in examples/pom.xml (and not in the top-level pom.xml).

**Comment by rnc** [comment]
Fixed by PR #376 and #375
