### ISSUE TITLE
Q: Automatic dependency resolution of SNAPHOT's

### ISSUE THREAD

**Issue by torsten-liermann** [release-engineering/pom-manipulation-ext#379]
We are wondering whether it makes sense to have a "Dependency Manipulation" mechanism that resolves SNAPSHOT dependencies of external artifacts similiar to the resolution of the project version?

Example:
`xyz:external-dependency:1.5-SNAPSHOT` => `xyz:external-dependency:1.5.0.11`

Thanks for your feedback,
Torsten

**Comment by rnc** [comment]
Isn't this what the http://www.mojohaus.org/versions-maven-plugin/ can do?

**Comment by torsten-liermann** [comment]
yes, but is lacking the ability to handle complex version-number schemes (like OSGI, prefix etc - as provided by this extension for the project version)

**Comment by torsten-liermann** [comment]
It seems that the versions-plugin is not capable of the same resolution mechanism as pme.

Versions can do `1.11.0.1-SNAPSHOT`to `1.11.0.1`. However, it can **NOT** do
`1.11-SNAPSHOT`to `1.11.0.1`. This is the functionality we are looking for.

**Comment by talksinmath** [comment]
It seems that `force-releases` does the trick. Unfortunately, this goal has to be run stand-alone.

**Comment by rnc** [comment]
Given that either `force-releases` or `use-release` from the versions-maven-plugin can be used (and could be used directly via e.g.  https://github.com/TimMoore/mojo-executor) I think that is a more suitable. Changing the SNAPSHOT component version part should just match the released version part - but I think you have a unusual scenario where you have `1.0-SNAPSHOT` and `1.0.0.Final` release version. 

 I am closing this for now *but*  saying that I'd be happy to take a look at any pull request you might have.
