### ISSUE TITLE
Dependency Analyzer REST endpoitns updated to '/reports/lookup/gavs'

### ISSUE THREAD

**Issue by fkujikis** [release-engineering/pom-manipulation-ext#415]
As a result of https://projects.engineering.redhat.com/browse/NCL-2114 the REST endpoints for '/reports/lookup/gavs' in Dependency Analyzer have changed, I was told that PME is affected by this.

A brief summary:

Changes allow narrowing down the products/versions to search for white artifacts by adding to the input types:
 - Set of productNames - can be empty
 - Set of productVersionIds - can be empty

POST /lookup/gavs
  - Input is now of type LookupGAVsReques, wrapping the GAV list and including productNames, productVersionIds
  - Example: /reports/lookup/gavs/guava13.json
  - Example: /reports/lookup/gavs/guava13List.json

For sample inputs look at the *.json file updates here: 
https://github.com/project-ncl/dependency-analysis/pull/320/files

**Comment by rnc** [comment]
Fixed now
