### ISSUE TITLE
dependencyExclusion should be called dependencyOverride

### ISSUE THREAD

**Issue by pgier** [release-engineering/pom-manipulation-ext#434]
Several places in the docs refer to using "dependencyExclusion" properties to override dependency versions.  I think this feature would be more intuitive if the property prefix was called "dependencyOverride" instead of "dependencyExclusion".  If the property prefix is changed to "dependencyOverride", maybe dependencyExclusion can be used as an alias to retain compatibility with previous build configs.

**Comment by rnc** [comment]
I agree that its not immediately intuitive; historical usage/development.

Can look at feasibility of an alias for dependencyOverride.

**Comment by rnc** [comment]
@pgier  Is https://github.com/release-engineering/pom-manipulation-ext/pull/435 sufficient?

**Comment by rnc** [comment]
Fixed by #435
