### ISSUE TITLE
PME invalid alteration of <Import-Package>

### ISSUE THREAD

**Issue by paulgallagher75** [release-engineering/pom-manipulation-ext#460]
When building bonecp using PME to make some small changes, It alters the Import-Package and looks to have added an extra org.springframework*;version=" in the CDATA section  :

Its reproducible by adding this section to the integration-test/src/it/cdata/pom.xml test

            <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
                <configuration>
                    <instructions>
                        <Import-Package>org.springframework*;version="<![CDATA[$<range;[==,=+);${spring.version}>]]>",org.apache.commons.logging;version="[1.1,2)",*</Import-Package>
                    </instructions>
                </configuration>
            </plugin>

GETS CHANGED TO :

            <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
                <configuration>
                    <instructions>
                        <Import-Package>org.springframework*;version="<![CDATA[org.springframework*;version="$<range;[==,=+);${spring.version}>",org.apache.commons.logging;version="[1.1,2)",*]]>",org.apache.commons.logging;version="[1.1,2)",*</Import-Package>
                    </instructions>
                </configuration>
            </plugin>

**Comment by rnc** [comment]
I think this is an issue in https://github.com/Commonjava/maven-model-jdom-support ; probably within WriterUtils within the code where I last made changes on CDATA.

**Comment by rnc** [comment]
https://github.com/Commonjava/maven-model-jdom-support/pull/11

**Comment by rnc** [comment]
Fixed by #462
