### ISSUE TITLE
RepoAndReportingRemovalManipulator Issues

### ISSUE THREAD

**Issue by rnc** [release-engineering/pom-manipulation-ext#478]
Various issues reported by @JonathanChristison

1. removal-backup-settings is not very configurable and is not documented
2. Writes an empty settings file.
3. Writes a settings file without a license (breaks RAT plugin).

And when diagnosing also spotted:

4. ignorelocalhost configuration is incorrect
5. Tests are not catching boolean errors

**Comment by rnc** [comment]
Backup settings originated in #172

**Comment by rnc** [comment]
@jdcasey Any opinions on adding a default license to the generated settings.xml ? It would avoid errors with the RAT plugin

**Comment by rnc** [comment]
After discussions with John we decided to remove the ability to automatically add a license (complexity over license formats / potential intermingling of license types etc)  ; recommendation instead is to use plugin-removal and remove the RAT plugin

**Comment by rnc** [comment]
One potential discussion issue: should we default the backup settings file creation to `off` or `on` ? 

@jdcasey @jcoleman0redhat0com @JonathanChristison Thoughts? Note: as the setting was undocumented previously we could actually change it ;-)

**Comment by jonathanchristison** [comment]
Based on my in depth knowledge of the meta files PME produces :wink: (I had never actually noticed them before RAT started complaining about them!) 

I'd say `on`  is better based on my "more metadata is always better" mantra, perhaps its not well used at the minute but if the PME altered sources are ever used in isolation they're pretty important for build reproducibility outside RH build infrastructure.

I think the discussion about alternatives to the current source archive generation, not that there's anything particularly wrong with it at the minute, is too wider scope for this GH issue but I have a few over engineered suggestions i'll write up :neckbeard:

**Comment by jcoleman0redhat0com** [comment]
My preferences:
  off by default
  contains license text

**Comment by rnc** [comment]
@jcoleman0redhat0com  @jonathanchristison  Perhaps its worth spawning a separate issue to discussing licensing injection as that covers multiple files (metadata / bom / settings ) and it would be preferable to be consistent.

**Comment by rnc** [comment]
Fixed by https://github.com/release-engineering/pom-manipulation-ext/pull/479
