### ISSUE TITLE
Consider whether to license PME injected files

### ISSUE THREAD

**Issue by rnc** [release-engineering/pom-manipulation-ext#483]
New files that PME injects can be
* BOM
* Build metadata
* settings.xml

Spawned from #478 ; should we license these or not? Thoughts:

* Potential conflict with existing project license
* May solve Apache RAT plugin errors.

**Comment by jdcasey** [comment]
It's probably way too much work (and potential for new bugs, really), but if we really wanted to we could probably parse the license section of the pom.xml, retrieve the license text from that, and add it to the generated files.

However, it would mean handling the different comment formats (and accommodating new ones in case we ever add more injected/generated file types). It would also mean dealing with pom.xml files that don't declare a license section...or that do include a LICENSE.txt or whatever.

There are so many variations to this, and I sort of don't see the value in preserving the rat functionality. If we put a rat-skip parameter in a profile and use that to build, it would always be possible for some post-processing step to re-enable it and run rat checks.

Thoughts?

**Comment by rnc** [comment]
@jdcasey For the RAT plugin, we could always configure it to be removed via the plugin-removal system - it does not cover cases where there is a single top level LICENSE file and the source code is covered via that.

While its perfectly possible to inject a license into the settings.xml, bom.xml, and build.metadata it would be curious if the project is licensed as e.g. LGPL and a few files are then licensed as Apache 2 (for instance). 

Therefore I think I'd be happy to leave this and close as won't fix for the moment?

**Comment by jdcasey** [comment]
works for me
