### ISSUE TITLE
Assert in POM that the extension is active

### ISSUE THREAD

**Issue by ahgittin** [release-engineering/pom-manipulation-ext#574]
I'd like to make it so a `mvn install` _fails_ if this extension is not active.  Is this possible?

From what I could tell it mainly relies on properties, which means if someone builds without this extension (but with the properties) they'll get a simple build _without_ the extension behaviour applied.

I'd like to prevent that (actually have a profile which prevents that) causing the build to fail if run in an environment where this extension is not installed.

(Apologies if raising an issue is premature but I didn't see an IRC link.  The project nicely addresses a pain point we have in Apache Brooklyn, with a more maintainable approach than changing versions forwards and backwards!  Many thanks for this and for any input into this question!)

**Comment by rnc** [comment]
Hi. 
Thats a really interesting idea! 

Normally when PME runs, it detects if its already been run (assuming a `mvn clean` has not been done) and will not run again by writing out marker files. This I have just realised is _not_ well documented so I'll have to improve that! Essentially in the top level target directory it writes out "pom-manip-ext-marker.txt" so it can detect whether it has been run already. It also writes out a JSON file with the root resulting GAV.

I wonder if you could write an enforcer rule that looks for the presence of this file and aborts if its not there?

( ps I am actually on freenode IRC under 'ncross' currently on #jacorb )

**Comment by rnc** [comment]
I have added an example of using a profile with the Maven Enforcer rule for PME here : https://github.com/rnc/pme-example/blob/enforcerPME/pom.xml
