### ISSUE TITLE
PME should minimize formatting changes to the files

### ISSUE THREAD

**Issue by orpiske** [release-engineering/pom-manipulation-ext#637]
When PME changes the files it also changes the formatting elements for some items. This makes reviewing PME changes harder, because it tends to change items that are unrelated to the actual changes in place. Here's a couple of examples taken from a diff of ours:

Before PME:
```
<?xml version="1.0"?>
```

After PME:
```
<?xml version="1.0" encoding="UTF-8"?>
```

Before PME:
```
<Import-Package>
  javax.ws.rs.*;version="[1.1,3)",
  org.apache.cxf.*;version="[2,4)",
</Import-Package>
```

After PME:
```
<Import-Package>javax.ws.rs.*;version="[1.1,3)",
    org.apache.cxf.*;version="[2,4)",</Import-Package>
<Export-Package>org.apache.cxf.samples.failover.jaxws</Export-Package>
```

Before PME: 
```<ignore />```

After PME:
```<ignore></ignore>```

We would like to request that PME refrain from doing these type of changes or, at least, provide a way that users can control how it will handle formatting of the elements it touches.

**Comment by grgrzybek** [comment]
:+1:

**Comment by rnc** [comment]
Yes, I am aware its not quite perfect. The code that writes out the poms is in https://github.com/release-engineering/pom-manipulation-ext/blob/master/io/src/main/java/org/commonjava/maven/ext/io/PomIO.java#L176 and that relies on https://github.com/Commonjava/maven-model-jdom-support/ 

Any contributions to improve its output would be much appreciated :-)

**Comment by rnc** [comment]
@orpiske @grgrzybek #773 tries to improve this. I would appreciate it if you could try it out to see if it helps for you. I think for those two above cases it does resolve them.
