### ISSUE TITLE
system properties in format -Dkey cause PME to fail, -Dkey=value is needed

### ISSUE THREAD

**Issue by Ladicek** [release-engineering/pom-manipulation-ext#797]
I often use system properties in format `-Dkey` in Maven invocations, e.g. `mvn clean install ... -Dswarm.product.build`, and I tend to use the same for PME invocations. This used to work fine, but starting with PME 4.1, I get this error message:

```
Value for option option '-D' (<String=String>) should be in KEY=VALUE format but was swarm.product.build
Usage: PME [-dhptV] [--printManipulatorOrder] [-f=<target>] [-l=<logFile>]
           [-s=<settings>] [-D=<String=String>]... [-P=<profiles>[,
           <profiles>...]]...
CLI to run PME
...
```

I could work around it by using `-Dswarm.product.build=true`, but that shouldn't be necessary. Seems like a bug to me.

**Comment by rnc** [comment]
Thanks for the report. In 4.1 we switched to using picocli (which is also what GME and Bacon uses). As https://picocli.info/#_arrays_collections_maps requires a '=' to differentiate the key/value pair that is why it fails. I think all you need to add is `-Dswarm.product.build=` to make it acceptable and then I can see
```
[picocli INFO] Putting [swarm.product.build : ] in LinkedHashMap<String, String> field java.util.Properties org.commonjava.maven.ext.cli.Cli.userProps for option -D on Cli@4b952a2d
```
I therefore think this isn't a bug but by design.

**Comment by Ladicek** [comment]
Too bad :-( Thanks anyway.

**Comment by dwalluck** [comment]
@rnc @Ladicek Something we could ask picocli upstream how to handle. I can make a ticket.

**Comment by dwalluck** [comment]
@Ladicek It's been three months, but support for this was added upstream in the latest picocli https://github.com/remkop/picocli/issues/1214 so that we can now support it with a simple change to the `@Option` annotation.

**Comment by Ladicek** [comment]
That would be nice, but I think I've accommodated for the change everywhere, so I'll leave the decision up to you :-)
