### ISSUE TITLE
Project version manipulation not working (?!?)

### ISSUE THREAD

**Issue by CeddaerrixGE** [release-engineering/pom-manipulation-ext#832]
I have set the _pom-manipulation-ext_ into _.mvn\extensions.xml_ with 
```
<extensions xmlns="http://maven.apache.org/EXTENSIONS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/EXTENSIONS/1.0.0 http://maven.apache.org/xsd/core-extensions-1.0.0.xsd">
  <extension>
    <groupId>org.commonjava.maven.ext</groupId>
    <artifactId>pom-manipulation-ext</artifactId>
    <version>4.3</version>
  </extension>
</extensions>
```

From the root of the multi-project project,  have then run the following:
`mvn -DversionSuffix=Some-Suffix clean install -e -B -f pom.xml -pl :project-common -am -P<some profiles> -s settings-maven.xml`

In the target folder, the package remains: _project-common-3.4.0-SNAPSHOT.jar_ and not _project-common-3.4.0-SNAPSHOT-Some-Suffix.jar_

Should not it behave as if having the _pom-manipulation-ext-4.3.jar_ was in the _%MAVEN_HOME\lib\ext_ directory?

**Comment by rnc** [comment]
I don't think we have tested it as a core extension as opposed to a lib/ext. Is this use-case something you would need?

You may find it easier to use it directly as a CLI tool (which is the primary mechanism we are currently using it with) ; see https://release-engineering.github.io/pom-manipulation-ext/#installation-as-cli-tool

**Comment by CeddaerrixGE** [comment]
> I don't think we have tested it as a core extension as opposed to a lib/ext. Is this use-case something you would need?
> 
> You may find it easier to use it directly as a CLI tool (which is the primary mechanism we are currently using it with) ; see https://release-engineering.github.io/pom-manipulation-ext/#installation-as-cli-tool

I have made it work with 'lib/ext'...
Still, I would have found it more elegant and convenient to have it configured into _.mvn\extensions.xml_ on the project SCM repo, thus not to have to find out where is M2_HOME on a Jenkins agent to have the jar copied into 'lib/ext' for pipelines using that extension

**Comment by rnc** [comment]
Understand :-) We tend to use with the CLI rather than lib/ext as such. Unfortunately it seems the Maven documentation conflicts between https://maven.apache.org/examples/maven-3-lifecycle-extensions.html and https://maven.apache.org/maven-jsr330.html and I have not checked if the latter supports lifecycle extensions.

**Comment by rnc** [comment]
Actually scratch that. I _think_ I may have found a way forward after experimenting with https://github.com/khmarbaise/test-maven-eventspy It looks like the interactions with the shade plugin causes failures in the injection (although I still hold its not particularly well documented!!)

**Comment by rnc** [comment]
One step forward, two back. I can now get it to pick up the extension within `.mvn/extensions.xml` but it gets classloader issues e.g.
```mvn -DversionSuffix=redhat-1
[INFO] Running Maven Manipulation Extension (PME) 4.4-SNAPSHOT ( SHA: 98d8b624 )
[INFO] Running manipulator org.commonjava.maven.ext.core.impl.InitialGroovyManipulator
[INFO] Running manipulator org.commonjava.maven.ext.core.impl.RangeResolver
[INFO] Running manipulator org.commonjava.maven.ext.core.impl.RESTBOMCollector
[INFO] Running manipulator org.commonjava.maven.ext.core.impl.ProfileInjectionManipulator
[INFO] Running manipulator org.commonjava.maven.ext.core.impl.SuffixManipulator
[INFO] Running manipulator org.commonjava.maven.ext.core.impl.RelocationManipulator
[INFO] Running manipulator org.commonjava.maven.ext.core.impl.RESTCollector
[INFO] Running manipulator org.commonjava.maven.ext.core.impl.ProjectVersioningManipulator
[INFO] Version Manipulator: Calculating the necessary versioning changes.
[INFO] Looking for new version: org.commonjava.maven.ext.integration-test:simple-numeric-override:1.0 (found: 1.0.0.redhat-1)
[INFO] Changed main version in org.commonjava.maven.ext.integration-test:simple-numeric-override:1.0.0.redhat-1 [pom=/home/rnc/Work/PME/pom-manipulation-ext/integration-test/target/it-ext/simple-numeric-with-maven-extensions/pom.xml]
[INFO] Running manipulator org.commonjava.maven.ext.core.impl.ParentInjectionManipulator
[INFO] Running manipulator org.commonjava.maven.ext.core.impl.PropertyManipulator
[INFO] Running manipulator org.commonjava.maven.ext.core.impl.PluginManipulator
[INFO] Running manipulator org.commonjava.maven.ext.core.impl.DependencyManipulator
[INFO] Running manipulator org.commonjava.maven.ext.core.impl.RepoAndReportingRemovalManipulator
[INFO] Running manipulator org.commonjava.maven.ext.core.impl.DependencyRemovalManipulator
[INFO] Running manipulator org.commonjava.maven.ext.core.impl.PluginRemovalManipulator
[INFO] Running manipulator org.commonjava.maven.ext.core.impl.NexusStagingMavenPluginRemovalManipulator
[INFO] Running manipulator org.commonjava.maven.ext.core.impl.ProfileRemovalManipulator
[INFO] Running manipulator org.commonjava.maven.ext.core.impl.PluginInjectingManipulator
[INFO] Running manipulator org.commonjava.maven.ext.core.impl.RepositoryInjectionManipulator
[INFO] Running manipulator org.commonjava.maven.ext.core.impl.ProjectVersionEnforcingManipulator
[INFO] Running manipulator org.commonjava.maven.ext.core.impl.DistributionEnforcingManipulator
[INFO] Running manipulator org.commonjava.maven.ext.core.impl.BOMBuilderManipulator
[INFO] Running manipulator org.commonjava.maven.ext.core.impl.JSONManipulator
[INFO] Running manipulator org.commonjava.maven.ext.core.impl.XMLManipulator
[INFO] Running manipulator org.commonjava.maven.ext.core.impl.FinalGroovyManipulator
[INFO] Maven-Manipulation-Extension: Rewrite changed: [org.commonjava.maven.ext.integration-test:simple-numeric-override:1.0.0.redhat-1 [pom=/home/rnc/Work/PME/pom-manipulation-ext/integration-test/target/it-ext/simple-numeric-with-maven-extensions/pom.xml]]
### PClassloader : ClassRealm[plexus.core, parent: null] and class org.codehaus.plexus.util.xml.Xpp3Dom and 238308051
### XClassloader : ClassRealm[coreExtension>org.commonjava.maven.ext:pom-manipulation-ext:4.4-SNAPSHOT, parent: ClassRealm[plexus.core, parent: null]] and class org.codehaus.plexus.util.xml.Xpp3Dom and 1665525689
[ERROR] Extension failure
java.lang.ClassCastException: org.codehaus.plexus.util.xml.Xpp3Dom cannot be cast to org.codehaus.plexus.util.xml.Xpp3Dom
    at org.commonjava.maven.ext.common.jdom.JDOMModelConverter.updatePlugin (JDOMModelConverter.java:1511)
    at org.commonjava.maven.ext.common.jdom.JDOMModelConverter.iteratePlugin (JDOMModelConverter.java:537)
```

(cc @dwalluck )

**Comment by rnc** [comment]
I have submitted https://issues.apache.org/jira/browse/MNG-7160 to see whether this is a Maven problem or there is something we have configured incorrectly.
