### ISSUE TITLE
Overwriting pom file should be optional

### ISSUE THREAD

**Issue by tisoft** [release-engineering/pom-manipulation-ext#965]
Currently the pom.xml is overwritten with the changed maven model. I would like the changes to be in-memory only. 

For example the https://github.com/qoomon/maven-git-versioning-extension does it that way.

To stay backwards compatible, this could be a configuration setting, defaulting to the current behavior of overwriting the pom.

**Comment by rnc** [comment]
Can you clarify why you need that and how you would intend to use it?

**Comment by tisoft** [comment]
We have a parent project with several submodules. One of those modules is generated by a 3rd party application. That module does not have the parent pom as parent. That is fine as long as it is only loaded from within the 3rd party application. But as soon as we do a full build, our parent pom must be injected into the module pom, so that for example our deployment configuration is used. This works fine with this extension, but the pom is then rewritten on the disk. If you now load the project back in the application, that fails, because the application does not support our parent pom settings. And it happens, that the changed file gets checked into git, since it is marked as changed and the developers sometimes forget, that changes for that pom may not be checked in, if they were not made from within the 3rd party application. Then someone must manually revert those changes.

Clearly the 3rd party application is to blame here, but there is nothing I can do about that. This plugin works great in fixing the generated pom, the only problem is, that it gets written to disk. 😄

**Comment by rnc** [comment]
@tisoft I see (sort of :-) ). 

* I presume you are using this as a Maven extension? i.e. the CLI option wouldn't work for your use-case.
* Can you show the project (if possible) and PME configuration you are using?

While not writing the changes back to pom is unusual if there is a use-case for it then I can take a look - although I don't think it makes sense if the tool is running as a CLI.

**Comment by tisoft** [comment]
Yeah, I'm using it as maven extension. Would not make sense for CLI.

I can't share the original project, but I'll try to create a little demo project later.

**Comment by rnc** [comment]
Another question - currently PME outputs various summary logging (and optionally writes them to disk) within this block https://github.com/release-engineering/pom-manipulation-ext/blob/main/core/src/main/java/org/commonjava/maven/ext/core/ManipulationManager.java#L231  While I don't think writing to disk is useful in this context _maybe_ a summary of the in-memory changes might be useful - thoughts?

**Comment by tisoft** [comment]
The mentioned git extensions does output the resulting pom in a different file, that is very helpful for debugging, since you can see, what the actual maven model looked like. Maybe that could also be implemented here.

The logging output can also be written, as it is put into the target directory anyway and doesn't interfere with anything.

**Comment by tisoft** [comment]
Unfortunately I didn't work on my first try. I'll have a look into it, if it's caused by something special, I'm doing.

**Comment by rnc** [comment]
@tisoft It does have to be activated by a flag - see https://github.com/release-engineering/pom-manipulation-ext/pull/970/files#diff-dffc8b420200d550c457a1ef2a95921cd59da0e03d0d5e320c75b5ec63f1a7d6R106

**Comment by rnc** [comment]
@tisoft :-) If you do find a problem and can provide a reproducer please let me know or have a debug log available - that might help to reveal what is happening.

**Comment by rnc** [comment]
@tisoft Any update please?

**Comment by rnc** [comment]
@tisoft I plan to do a release soon so unless I hear otherwise I will probably just merge that code.

**Comment by tisoft** [comment]
@rnc Sorry for not responding. I'm currently very busy with other stuff. Will test the released version again in the future and will open a new issue, if I can't get it to work.

Thanks for implementing it!
